// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPs6DuJynNQeSJG5eFqbx7v3ypXLH3sRQ',
    appId: '1:42479048371:web:bc155323fda942a022c2c6',
    messagingSenderId: '42479048371',
    projectId: 'grocery-app-93d25',
    authDomain: 'grocery-app-93d25.firebaseapp.com',
    storageBucket: 'grocery-app-93d25.appspot.com',
    measurementId: 'G-127XD9BGCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTSa7Ge8-Sf-kJbcHJO2cFfq3fdxEVhJ0',
    appId: '1:42479048371:android:aafde1ea4b754de322c2c6',
    messagingSenderId: '42479048371',
    projectId: 'grocery-app-93d25',
    storageBucket: 'grocery-app-93d25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Q3Hts375nlPpTiRqiBW-SR5N8uHT8RA',
    appId: '1:42479048371:ios:7909a124fda92c0822c2c6',
    messagingSenderId: '42479048371',
    projectId: 'grocery-app-93d25',
    storageBucket: 'grocery-app-93d25.appspot.com',
    iosClientId: '42479048371-6i8qbd27g88m9nqu6un5gtmu1v68gcmd.apps.googleusercontent.com',
    iosBundleId: 'com.policy.kipsy',
  );
}
